version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgres/data

volumes:
  postgres:
    